"""initial schema

Revision ID: d2c72f65c70a
Revises: 
Create Date: 2026-06-03 21:46:22.167068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c72f65c70a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_supabase_uid'), ['supabase_uid'], unique=True)

    op.create_table('animal_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_classes_user_id'), ['user_id'], unique=False)

    op.create_table('feed_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.Enum('lbs', 'kg', name='feed_unit'), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('par_level', sa.Float(), nullable=False),
    sa.Column('current_on_hand', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_types_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('low_feed', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_feed_type_id'), ['feed_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['animal_class_id'], ['animal_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeds_animal_class_id'), ['animal_class_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'feeding', 'adjustment', name='inventory_transaction_type'), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_feed_type_id'), ['feed_type_id'], unique=False)

    op.create_table('flocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.Enum('layer', 'breeder', 'meat', 'mixed', name='flock_designation'), nullable=False),
    sa.Column('pen_name', sa.String(length=120), nullable=True),
    sa.Column('current_headcount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flocks_breed_id'), ['breed_id'], unique=False)

    op.create_table('breeding_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('male_id', sa.Integer(), nullable=True),
    sa.Column('female_id', sa.Integer(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('expected_hatch_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['female_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['male_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_logs_flock_id'), ['flock_id'], unique=False)

    op.create_table('casualty_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casualty_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casualty_logs_flock_id'), ['flock_id'], unique=False)

    op.create_table('feed_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flock_id', 'feed_type_id', name='uq_feed_assignment_flock_feed_type')
    )
    with op.batch_alter_table('feed_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_assignments_feed_type_id'), ['feed_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_assignments_flock_id'), ['flock_id'], unique=False)

    op.create_table('feeding_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('input_method', sa.Enum('manual', 'scale', name='feeding_input_method'), nullable=False),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feeding_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_events_feed_type_id'), ['feed_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feeding_events_flock_id'), ['flock_id'], unique=False)

    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_feed_cost', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('net_pl', sa.Float(), nullable=False),
    sa.Column('cost_per_bird', sa.Float(), nullable=False),
    sa.Column('revenue_source', sa.Enum('egg_sales', 'meat_sales', 'other', name='revenue_source'), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_records_flock_id'), ['flock_id'], unique=False)

    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('egg_count', sa.Integer(), nullable=True),
    sa.Column('water_consumed', sa.Float(), nullable=True),
    sa.Column('avg_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_logs_flock_id'), ['flock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_logs_flock_id'))

    op.drop_table('production_logs')
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_records_flock_id'))

    op.drop_table('financial_records')
    with op.batch_alter_table('feeding_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_events_flock_id'))
        batch_op.drop_index(batch_op.f('ix_feeding_events_feed_type_id'))

    op.drop_table('feeding_events')
    with op.batch_alter_table('feed_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_assignments_flock_id'))
        batch_op.drop_index(batch_op.f('ix_feed_assignments_feed_type_id'))

    op.drop_table('feed_assignments')
    with op.batch_alter_table('casualty_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casualty_logs_flock_id'))

    op.drop_table('casualty_logs')
    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_logs_flock_id'))

    op.drop_table('breeding_logs')
    with op.batch_alter_table('flocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flocks_breed_id'))

    op.drop_table('flocks')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_feed_type_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeds_animal_class_id'))

    op.drop_table('breeds')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_feed_type_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('feed_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_types_user_id'))

    op.drop_table('feed_types')
    with op.batch_alter_table('animal_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_classes_user_id'))

    op.drop_table('animal_classes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
