services:
  db:
    image: postgres:16
    container_name: Flock-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Flock
      POSTGRES_USER: Flock
      POSTGRES_PASSWORD: Flock
    ports:
      - "5432:5432"
    volumes:
      - Flock_postgres_data:/var/lib/postgresql/data

volumes:
  Flock_postgres_data:
